title: "Handbook of Market Area and Accessibility Models"
description: "Market Area and Accessibility Models in the huff Python Package"
author: "Thomas Wieland"

defaults:
  - scope:
      path: ""
    values:
      layout: default

markdown: kramdown
kramdown:
  math_engine: mathjax