title: "Handbook of Market Area and Accessibility Models"
description: "Methodological handbook for the huff Python package"
author: "Thomas Wieland"

defaults:
  - scope:
      path: ""
    values:
      layout: default

markdown: kramdown
kramdown:
  math_engine: mathjax